---
- name: Windows install update and reobot  playbook
  hosts: all
  gather_facts: false

  tasks:
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: `*`
        reboot: yes
